let strip = neopixel.create(DigitalPin.P0, 10, NeoPixelMode.RGB)
basic.forever(function () {
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(500)
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Purple))
    strip.show()
    basic.pause(500)
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Yellow))
    strip.show()
    basic.pause(500)
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Green))
    strip.show()
    basic.pause(500)
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(500)
    strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Orange))
    strip.show()
    basic.pause(500)
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Violet))
    strip.show()
    basic.pause(500)
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Indigo))
    strip.show()
    basic.pause(500)
    strip.setPixelColor(8, neopixel.colors(NeoPixelColors.White))
    strip.show()
    basic.pause(500)
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(500)
    strip.showColor(neopixel.colors(NeoPixelColors.Black))
    strip.show()
    basic.pause(500)
})
